# Generated by Django 5.2.9 on 2025-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_price_alter_receipt_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='payment_qr/', verbose_name='QR-код для оплаты картой')),
                ('card_payment_message', models.CharField(default='Отсканируйте QR-код или приложите карту к терминалу', max_length=200, verbose_name='Сообщение при оплате картой')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки оплаты',
                'verbose_name_plural': 'Настройки оплаты',
            },
        ),
    ]
