# Generated by Django 5.2.7 on 2026-03-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Логин')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('is_success', models.BooleanField(default=False, verbose_name='Результат входа')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Пользовательский агент')),
            ],
            options={
                'verbose_name': 'Попытка входа',
                'verbose_name_plural': 'Попытки входа',
                'ordering': ['-timestamp'],
            },
        ),
    ]
